name: hom3-server

services:
  # Operation and maintenence
  cockpit-ws:
    container_name: cockpit-ws
    hostname: cockpit-ws
    image: fedora/cockpitws:latest
    pid: host
    privileged: true
    restart: unless-stopped
    volumes:
      - /:/host
    command:
      - '/continer/atomic-run'
      - '--local-ssh'

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros:latest
    restart: unless-stopped
    environment:
      CLEANUP: true
      INTERVAL: 3600
      LOG_LEVEL: info
      SELF_UPDATE: true
      IGNORE: "mongo influxdb postgres mariadb"
      TZ: "Europe/Berlin"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Network and accessibility
  ddclient:
    container_name: ddclient
    hostname: ddclient
    image: linuxserver/ddclient:latest
    restart: unless-stopped
    environment:
      PGID: 100
      PUID: 1050
      TZ: "Europe/Berlin"
    volumes:
      - /mnt/ddclient:/config:Z
    networks:
      - ddclient-net

  proxy-nginx:
    container_name: proxy-nginx
    hostname: proxy-nginx
    image: kricklen/proxy_nginx:latest
    restart: unless-stopped
    volumes:
      - /mnt/proxy/nginx:/etc/nginx/conf.d:Z
      - /mnt/proxy/certbot/conf:/etc/letsencrypt:z,ro
      - /mnt/proxy/certbot/www:/var/www/certbot:z,ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy-net
    depends_on:
      - cockpit-ws
      - nextcloud-web
      - web-nginx

  proxy-certbot:
    container_name: proxy-certbot
    hostname: proxy-certbot
    image: kricklen/proxy_certbot:latest
    restart: unless-stopped
    volumes:
      - /mnt/proxy/certbot/conf:/etc/letsencrypt:z
      - /mnt/proxy/certbot/www:/var/www/certbot:z
      - /mnt/proxy/certbot/lib:/var/lib/letsencrypt:Z
    networks:
      - proxy-net
    depends_on:
      - proxy-nginx

  # Nextcloud
  nextcloud-db:
    container_name: nextcloud-db
    hostname: nextcloud-db
    image: kricklen/nextcloud_db:latest
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - /mnt/nextcloud/db:/var/lib/mysql:Z
    networks:
      - nextcloud-db-net

  nextcloud-fpm:
    container_name: nextcloud-fpm
    hostname: nextcloud-fpm
    image: kricklen/nextcloud_fpm:latest
    restart: unless-stopped
    user: 1052:100
    volumes:
      - /mnt/nextcloud/www:/var/www/html:z
      - /mnt/downloads:/mnt/downloads:z
    networks:
      - nextcloud-db-net
      - nextcloud-ui-net
    depends_on:
      - nextcloud-db

  nextcloud-web:
    container_name: nextcloud-web
    hostname: nextcloud-web
    image: kricklen/nextcloud_nginx:latest
    restart: unless-stopped
    user: 1052:100
    volumes:
      - /mnt/nextcloud/www:/var/www/html:z,ro
      - /mnt/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf:z,ro
    networks:
      - nextcloud-ui-net
      - proxy-net
    depends_on:
      - nextcloud-fpm

  # Homepage
  web-fpm:
    container_name: web-fpm
    hostname: web-fpm
    image: kricklen/web_fpm:latest
    restart: unless-stopped
    user: 1058:100
    volumes:
      - /mnt/web/www:/var/www/html:z
    networks:
      - web-net

  web-nginx:
    container_name: web-nginx
    hostname: web-nginx
    image: kricklen/web_nginx:latest
    restart: unless-stopped
    user: 1058:100
    volumes:
      - /mnt/web/www:/var/www/html:z,ro
      - /mnt/web/nginx/nginx.conf:/etc/nginx/nginx.conf:z,ro
    networks:
      - web-net
      - proxy-net
    depends_on:
      - web-fpm

  # Files and media
  plex:
    container_name: plex
    hostname: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      PLEX_UID: 1054
      PLEX_GID: 100
      TZ: "Europe/Berlin"
      ADVERTISE_IP: "http://192.168.178.13:32400"
      ALLOWED_NETWORKS: "192.168.178.0/24,172.16.0.0/16"
    volumes:
      - /mnt/plex/config:/config:Z
      - /mnt/plex/transcode:/transcode:Z
      - /mnt/downloads:/downloads:z,ro
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - plex-net

  samba:
    container_name: samba
    hostname: samba
    image: dperson/samba:latest
    restart: unless-stopped
    volumes:
      - samba_etc:/etc:Z
      - samba_cache:/var/cache/samba:Z
      - samba_lib:/var/lib/samba:Z
      - samba_log:/var/log/samba:z
      - samba_run:/run/samba:Z
      - /mnt/downloads:/mnt/downloads:z
      - /mnt/home:/mnt/home:z
    ports:
      - 139:139
      - 445:445
    environment:
      TZ: "Europe/Berlin"
    command:
      - -u
      - markus;markus;1000;users
      - -s
      - Downloads;/mnt/downloads;yes;no;no;markus;markus
      - -s
      - Home;/mnt/home;yes;no;no;markus;markus
    networks:
      - samba-net

  tor_relay:
    container_name: tor_relay
    hostname: tor_relay
    image: kricklen/tor_relay:latest
    restart: unless-stopped
    user: 19001:users
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - 35278:35278
      - 35288:35288
    volumes:
      - /mnt/tor:/etc/tor:Z
      - /mnt/tor/data:/var/lib/tor/data:Z
      - /mnt/tor/run:/var/run/tor:Z
    networks:
      - tor-net

networks:
  ddclient-net:
  nextcloud-db-net:
  nextcloud-ui-net:
  plex-net:
  proxy-net:
  samba-net:
  tor-net:
  web-net:

volumes:
  samba_etc:
  samba_cache:
  samba_lib:
  samba_log:
  samba_run: