# Include tasks for creating proxy
- name: Install proxy
  import_tasks: "install.yml"
  when: run_mode == "install"

- name: Uninstall proxy
  import_tasks: "uninstall.yml"
  when: run_mode == "uninstall"
