# Find configs
- name: Find Files - fail2ban configs
  find:
    paths: "{{ file_path }}"
    patterns: '*'
    recurse: yes
  register: files_to_delete

# Delete configs
- name: Delete Files - fail2ban configs
  file:
    state: absent
    path: "/etc/fail2ban/{{ item.path | relpath(file_path) }}"
  loop: "{{ files_to_delete.files }}"

# Restart fail2ban
- name: Restart Service - fail2ban
  systemd:
    state: restarted
    name: fail2ban
