version: "3"

services:

  # cockpit-ws doesn't run in docker stack atm.
  # Run as separate docker container, which might be better actually

  ddclient:
    hostname: ddclient
    image: local/ddclient:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s
    volumes:
      - "${ddclient_config_dir}/ddclient.conf:/etc/ddclient.conf:Z"
    environment:
      PGID: "${ddclient_group_id}"
      PUID: "${ddclient_user_id}"
      TZ: "${timezone}"
    networks:
      - ddclient_net

  # Start nextcloud-db docker container
  nextcloud-db:
    hostname: nextcloud-db
    image: mariadb:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s
    environment:
      "MYSQL_RANDOM_ROOT_PASSWORD": "yes"
    volumes:
      - "${nextcloud_db_dir}:/var/lib/mysql:Z"
    networks:
      - nextcloud_net

# Start nextcloud-fpm docker container
  nextcloud-fpm:
    hostname: nextcloud-fpm
    image: local/nextcloud_fpm:latest
    user: "${nextcloud_user_id}:${nextcloud_group_id}"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s
    volumes:
      - "${nextcloud_www_dir}:/var/www/html:z"
      - "/mnt/downloads:/mnt/downloads:z"
    networks:
      - name: nextcloud_net

# Start nextcloud-web (nginx) to serve static html content
  nextcloud-web:
    hostname: nextcloud-web
    image: local/nextcloud_nginx:latest
    user: "${nextcloud_user_id}:${nextcloud_group_id}"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s
    volumes:
      - "${nextcloud_www_dir}:/var/www/html:z,ro"
      - "${nextcloud_nginx_dir}/nginx.conf:/etc/nginx/nginx.conf:z,ro"
    networks:
      - proxy_net
      - nextcloud_net


networks:
  ddclient_net:
  nextcloud_net:
  proxy_net: