version: "3.7"

services:

  cockpit_ws:
    name: cockpit_ws
    hostname: cockpit_ws
    image: docker.io/cockpit/ws:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: 1
          memory: 500M
      restart_policy:
        condition: unless-stopped
    pid_mode: host
    privileged: yes
    volumes:
      - /:/host
    command:
      - "/container/atomic-run"
      - "--local-ssh"

  ddclient:
    hostname: ddclient
    image: local/ddclient:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: unless-stopped
    volumes:
      - "${ddclient_config_dir}/ddclient.conf:/etc/ddclient.conf:Z"
    env:
      PGID: "${ddclient_group_id}"
      PUID: "${ddclient_user_id}"
      TZ: "${timezone}"
    purge_networks: yes
    networks:
      - name: ddclient_net

networks:
  ddclient_net: