version: "3"

services:

  # cockpit-ws doesn't run in docker stack atm.
  # Run as separate docker container, which might be better actually

  ddclient:
    hostname: ddclient
    image: local/ddclient:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s
    volumes:
      - "${ddclient_config_dir}/ddclient.conf:/etc/ddclient.conf:Z"
    environment:
      PGID: "${ddclient_group_id}"
      PUID: "${ddclient_user_id}"
      TZ: "${timezone}"
    networks:
      - ddclient_net

networks:
  ddclient_net:
