
# fail2ban docker manual:
# https://www.the-lazy-dev.com/en/install-fail2ban-with-docker/
---
- hosts: localhost
  connection: local

  vars:
    test_var: abc
    domain_list:
      [
        {
          name: "abc",
          token: "123",
          email: "foo"
        },
        {
          name: "def",
          token: "456",
          email: "bar"
        }
      ]
    domain_dict:
      hom3.spdns.org:
        token: 123
        email: a@b.c
      cloud-hom3.spdns.org:
        token: 456
        email: d@e.f
    paths:
      - path a
      - path b

  tasks:
    - name: Test list iteration
      debug:
        msg: "{{ item[0].name }} : {{ item[0].email }} : {{ item[1] }}"
      with_nested:
        - "{{ domain_list }}"
        - "{{ paths }}"
    - name: Test list concat
      debug:
        msg: "{{ item[0] | join(\" \") }}"
      with_nested:
        - "{{ domain_list }}"
    - name: Test dict loop
      debug:
        msg: "{{ item.key }} : {{ item.value.token }}"
      loop: "{{ domain_dict | dict2items }}"
    - name: Test dict loop2
      debug:
        msg: "{{ item.0 }} : {{ item.1 }}"
      loop: "{{ domain_dict | product(paths) | list }}"
    - name: Test dict loop3
      debug:
        msg: "{{ domain_dict | list | join(' ') }}"
    - name: Test dict loop4
      debug:
        msg: "{{ item.key }}"
      loop: "{{ domain_dict | dict2items }}"
    - name: Test dict loop5
      debug:
        msg: "{{ test_var }}/{{ item.0 }}/{{ item.1.key }}"
      loop: "{{ [ 'live', 'arch' ] | product(domain_dict | dict2items) | list }}"
