- name: Build Image - nextcloud_fpm
  docker_image:
    path: "{{ role_path }}/nextcloud_fpm"
    name: local/nextcloud_fpm
    tag: latest

- name: Build Image - nextcloud_nginx
  docker_image:
    path: "{{ role_path }}/nextcloud_nginx"
    name: local/nextcloud_nginx
    tag: latest

- name: Build Image - proxy_certbot
  docker_image:
    path: "{{ role_path }}/proxy_certbot"
    name: local/proxy_certbot
    tag: latest

- name: Build Image - proxy_nginx
  docker_image:
    path: "{{ role_path }}/proxy_nginx"
    name: local/proxy_nginx
    tag: latest

- name: Build Image - samba
  docker_image:
    path: "{{ role_path }}/samba"
    name: local/samba
    tag: latest
