- name: Build Image - ddclient
  docker_image:
    path: "{{ role_path }}/ddclient"
    name: local/ddclient
    force: yes

- name: Build Image - nextcloud_fpm
  docker_image:
    path: "{{ role_path }}/nextcloud_fpm"
    name: local/nextcloud_fpm
    force: yes

- name: Build Image - nextcloud_nginx
  docker_image:
    path: "{{ role_path }}/nextcloud_nginx"
    name: local/nextcloud_nginx
    force: yes

- name: Build Image - web_nginx
  docker_image:
    path: "{{ role_path }}/web_nginx"
    name: local/web_nginx
    force: yes

- name: Build Image - web_fpm
  docker_image:
    path: "{{ role_path }}/web_fpm"
    name: local/web_fpm
    force: yes

- name: Build Image - proxy_certbot
  docker_image:
    path: "{{ role_path }}/proxy_certbot"
    name: local/proxy_certbot
    force: yes

- name: Build Image - proxy_nginx
  docker_image:
    path: "{{ role_path }}/proxy_nginx"
    name: local/proxy_nginx
    force: yes

- name: Build Image - samba
  docker_image:
    path: "{{ role_path }}/samba"
    name: local/samba
    force: yes

- name: Build Image - tor_relay
  docker_image:
    path: "{{ role_path }}/tor_relay"
    name: local/tor_relay
    force: yes
